### ISSUE TITLE
Make test macro EXPECT_RANGE_EQUAL available 

### ISSUE THREAD

**Issue by smehringer** [seqan/app-template#23]
By copying it over from seqan3 I guess.

For now I added the `test/include` directory to my include paths when building the tests so I can already use it but users won't know about this.

**Comment by eseiler** [comment]
Which test?

If you want to use it in the `cli_test`, it's already included via `#include "cli_test.hpp"`
For the `api_tests` you should be able to just use `#include <seqan3/test/expect_range_eq.hpp>` ?

**Comment by smehringer** [comment]
> For the `api_test`s.

Which test?

> For the api_tests, you should be able to just use #include <seqan3/test/expect_range_eq.hpp> ?

This only works, as I mentioned, if you add the test include directory to cmake. (which was not the case by default for me)

**Comment by eseiler** [comment]
Ah ok.

https://github.com/seqan/app-template/blob/90659e3dacd4f7ae7c52149eb08517b822a38ad7/test/CMakeLists.txt#L40-L46

Should work if you either copy the `target_include_directories(${target} PUBLIC "${SEQAN3_CLONE_DIR}/test/include") ` to the `API_TEST` section there, or just put the `target_include_directories(${target} PUBLIC "${SEQAN3_CLONE_DIR}/test/include")` before or after the if/elseif/endif

**Comment by smehringer** [comment]
jup :)

Maybe this should be added by default?

**Comment by eseiler** [comment]
I'd say so but maybe there was a reason to not to include it...

**Comment by smehringer** [comment]
@marehr @joergi-w Any memories or feelings about this?

**Comment by joergi-w** [comment]
Yes I agree, you can make it available to all the tests by moving the respective line before the `if` statement.
